apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: vote
spec:
  # internal access only
  type: ClusterIP
  selector:
    label: db-deployment
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
    