apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: vote
spec:
  type: ClusterIP
  selector:
    label: redis-deployment
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
    