apiVersion: v1
kind: Service
metadata:
  name: result-service
  namespace: vote
spec:
  # public accessible
  type: NodePort
  selector:
    label: result-deployment
  ports:
    - protocol: TCP
      # access service inside cluster
      port: 5001
      # access pod
      targetPort: 80
      # access service outside cluster (Node)
      nodePort: 31001
