apiVersion: v1
kind: Service
metadata:
  name: vote-service
  namespace: vote
spec:
  # public accessible
  type: NodePort
  selector:
    label: vote-deployment
  ports:
    - protocol: TCP
      # access service inside cluster
      port: 5000
      # access pod
      targetPort: 80
      # access service outside cluster (Node)
      nodePort: 31000
    