apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: vote
spec:
  # number of pod
  replicas: 1
  selector:
    matchLabels:
      # deploy to pod
      label: worker
  template:
    # pod properties
    metadata:
      labels:
        label: worker
    spec:
      containers:
        - name: worker
          image: kodekloud/examplevotingapp_worker
          ports:
            - containerPort: 80
