# https://kubernetes.io/docs/concepts/configuration/secret/

apiVersion: v1
# store key-pair to ETCD and then either
# mount it separately from the pods that use them
# or save them as environment variables
kind: Secret
metadata:
  name: drupal-mysql-secret
type: Opaque
# base64 encryption
data:
  MYSQL_ROOT_PASSWORD: cm9vdF9wYXNzd29yZAo=
  MYSQL_DATABASE: ZHJ1cGFsLWRhdGFiYXNlCg==
  MYSQL_USER: cm9vdAo=

# override [data]
stringData:
  MYSQL_ROOT_PASSWORD: root_password
  MYSQL_DATABASE: drupal-database
  MYSQL_USER: root
