apiVersion: v1
kind: Service
metadata:
  name: drupal-service
spec:
  type: NodePort
  selector:
    app: drupal
  ports:
    # By default and for convenience,
    # the Kubernetes control plane
    # will allocate a port from a range
    # (default: 30000-32767)
    - protocol: TCP
      # access service inside cluster
      port: 80
      # access pod
      targetPort: 80
      # access service outside cluster (Node)
      nodePort: 30095