---
apiVersion: v1
# allocate any storage to be resouce of k8s
kind: PersistentVolume
metadata:
  name: drupal-mysql-pv
spec:
  # a way to describe the the storage
  storageClassName: local-storage
  capacity:
    storage: 5Gi # GiB
  # the storage will use one access mode when being mount
  # even if it supports more than one mode
  accessModes:
    # the volume can be mounted as read-write by a single node
    - ReadWriteOnce
  hostPath:
    path: /drupal-mysql-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-mysql-pvc
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
