# Role-based access control (RBAC)
# Role = namespace resource permission
# ClusterRole = !namespace resource permission
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: development
  name: developer-role
rules:
  - apiGroups: [""] #  core API group (rbac.authorization.k8s.io)
    resources: ["services","persistentvolumeclaims","pods"]
    verbs: ["get", "list", "create", "update", "patch", "watch", "delete"]
