apiVersion: v1
kind: Pod
metadata:
  name: gop-fileserver
  labels:
    app: gop-fileserver
spec:
  volumes:
    - name: data-store
      persistentVolumeClaim:
        claimName: data-pvc

  containers:
    - name: gob-fileserver
      image: kodekloud/fileserver
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /web
          name: data-store
